name: WindBrowser Hızlı Paketleyici (Ubuntu)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: WindOS Paketi Hazirla (.wind)
      run: |
        mkdir -p WindBrowser_WindOS
        cp windbrowser.py WindBrowser_WindOS/
        echo "AppName: WindBrowser" > WindBrowser_WindOS/manifest.txt
        echo "Core: WindOS V7" >> WindBrowser_WindOS/manifest.txt
        tar -czf WindBrowser.wind WindBrowser_WindOS

    - name: Paketi Cikti Olarak Ver
      uses: actions/upload-artifact@v4
      with:
        name: WindBrowser-Paketi
        path: WindBrowser.wind
