name: WindBrowser Otomatik Derleyici

on:
  push:
    branches: [ "main" ] # main dalına her kod attığında otomatik çalışır
  workflow_dispatch: # İstediğinde elinle de başlatabilmen için

jobs:
  build-and-release:
    runs-on: windows-latest # Derleme işlemini Windows sunucusunda yapar

    steps:
    - name: Kodları Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Motorları Yükle (PyQt5 & PyInstaller)
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine pyinstaller

    - name: Windows için .EXE Derle
      run: |
        pyinstaller --onefile --noconsole --name=WindBrowser windbrowser.py

    - name: WindOS için .WIND Paketini Hazırla
      shell: bash
      run: |
        # WindOS sistemi için kurulum klasör yapısını oluşturuyoruz
        mkdir -p WindBrowser_WindOS
        cp windbrowser.py WindBrowser_WindOS/
        echo "AppName: WindBrowser" > WindBrowser_WindOS/manifest.txt
        echo "Core: WindOS V7" >> WindBrowser_WindOS/manifest.txt
        
        # Bu klasörü WindOS çekirdeğinin tek tıkla okuyabileceği .wind paketine dönüştür
        tar -czf WindBrowser.wind WindBrowser_WindOS

    - name: Dosyaları GitHub'a Yükle (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: WindBrowser-Paketleri
        path: |
          dist/WindBrowser.exe
          WindBrowser.wind
